parameters:
#    ardetem_import.example.class: Ardetem\ImportBundle\Example

services:
#    ardetem_import.example:
#        class: %ardetem_import.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
