_admin_login_check:
    pattern:   /{_locale}/admin/login_check
    requirements:
        _locale: zh_CN|en|es|fr|pl|de|it
_admin_login:
    pattern:   /{_locale}/admin/login
    requirements:
        _locale: zh_CN|en|es|fr|pl|de|it
_admin_logout:
    pattern:   /{_locale}/admin/logout
    requirements:
        _locale: zh_CN|en|es|fr|pl|de|it
ardetem_import:
    resource: "@ArdetemImportBundle/Resources/config/routing.yml"
    prefix:   /

root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%/
        permanent: true

ardetem_sfere_locale:
    resource: "@ArdetemSfereBundle/Resources/config/routing.yml"
    prefix:   /{_locale}

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /{_locale}/admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /{_locale}/admin

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"
    prefix: /{_locale}/
sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /{_locale}/resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /{_locale}/profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /{_locale}/register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /{_locale}/profile