ardetem_sfere:
    resource: "@ArdetemSfereBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /
ardetem_sfere_category:
    resource: "@ArdetemSfereBundle/Controller/CategoryController.php"
    type:     annotation
    prefix:   /category
ardetem_sfere_subcategory:
    resource: "@ArdetemSfereBundle/Controller/SubCategoryController.php"
    type:     annotation
    prefix:   /subcategory
ardetem_sfere_product:
    resource: "@ArdetemSfereBundle/Controller/ProductController.php"
    type:     annotation
    prefix:   /product