services:
   kernel_request.listener:
       class: Ardetem\SfereBundle\Listener\KernelRequestListener
       tags:
           - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
   ardetem.sfere.admin.category:
      class: Ardetem\SfereBundle\Admin\CategoryAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: category, label: Category }
      arguments:
        - ~
        - Ardetem\SfereBundle\Entity\Category
        - ~ #ArdetemSfereBundle:CategoryAdmin
   ardetem.sfere.admin.subcategory:
      class: Ardetem\SfereBundle\Admin\SubCategoryAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: category, label: Sub Category }
      arguments:
        - ~
        - Ardetem\SfereBundle\Entity\SubCategory
        - ~ #ArdetemSfereBundle:SubCategoryAdmin
   ardetem.sfere.admin.product:
      class: Ardetem\SfereBundle\Admin\ProductAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Product, label: Product }
      arguments:
        - ~
        - Ardetem\SfereBundle\Entity\Product
        - ~
   ardetem.sfere.admin.document:
      class: Ardetem\SfereBundle\Admin\DocumentAdmin
      tags:
        - { name: sonata.admin, manager_type: orm, group: Document, label: Document }
      arguments:
        - ~
        - Ardetem\SfereBundle\Entity\Document
        - ~
   form.type.document.file:
       class: Ardetem\SfereBundle\Form\Type\DocumentFile
       tags:
           - { name: form.type, alias: admin_document_to_file }